In [2]:
import pandas as pd

In [4]:
# df = pd.read_csv("data/도서별 상세/NL_bo_species_master_new_2019_new.csv")

In [19]:
# df = df.dropna(subset=['?master_seq'])

In [6]:
df = pd.read_csv("data/도서 키워드/NL_BO_TAG_CLOUD4_202012-1.csv")

In [27]:

df['ONE_WGHTVAL_VALUE'].unique()

array([  0,   1,  53,  33,  20,  19,  16,  15,  14,  13,   9,  12,  11,
        10,   6,   8,   5,   7,   4,   3,   2,  49,  37,  32,  23,  22,
        35,  25,  24,  21,  77,  38,  17,  18,  81,  29,  26, 210,  46,
        30, 162,  31,  42,  62,  45,  34,  36,  52,  65,  27,  44,  28,
        39,  43,  50,  73,  86,  78,  63, 139, 217,  68, 164,  60,  41,
        90,  80,  51,  91, 130, 133, 264,  64,  47,  48,  87,  72,  57,
        40,  59,  95,  99, 126,  66,  94,  61,  55,  58,  74,  82,  97,
       112,  56,  76,  88,  54,  71, 116,  67,  83,  79,  69, 100, 119,
       142, 147, 121, 102,  75, 101,  70, 110, 122, 124, 125,  89,  85,
       148, 107, 128, 117,  98, 109, 158, 103,  92, 114,  84, 108, 113,
       111, 186, 150, 261, 170, 138, 104, 105, 141, 153, 120, 106, 115,
       152,  93, 173], dtype=int64)

In [31]:
df[df['ONE_WGHTVAL_VALUE'] == 53]

,ISBN_NO,WRD_NM,FQ_CO,ONE_WGHTVAL_VALUE,TWO_WGHTVAL_VALUE,THREE_WGHTVAL_VALUE
79,8809270742090,영화,53,53,0,0
20348,9788901059846,동영,53,53,0,0
45198,9791160560503,여행,53,53,0,0
56005,9791186712788,수학,53,53,0,0
60898,9788901042367,윌리,56,53,0,1
326805,9788901101156,환관,53,53,0,0
480663,9788901158693,바다,53,53,0,0
640788,9788915086791,제주,53,53,0,0
657391,9788919204030,피부,53,53,0,0
687221,9788925501147,만약,53,53,0,0
687458,9788925501154,만약,53,53,0,0
854883,9788925542904,남해안,53,53,0,0
862880,9788925543994,질문,53,53,0,0
867733,9788925544977,수학,53,53,0,0
1443863,9788954403238,생물법정,53,53,0,0
1474118,9788954413879,생물법정,53,53,0,0
1474597,9788954413886,생물법정,53,53,0,0
1475071,9788954413893,생물법정,53,53,0,0
1475544,9788954413909,생물법정,53,53,0,0
1481241,9788954414708,생물법정,53,53,0,0
1481742,9788954414715,생물법정,53,53,0,0
1482243,9788954414722,생물법정,53,53,0,0
1482735,9788954414739,생물법정,53,53,0,0
1483232,9788954414746,생물법정,53,53,0,0
1558079,9788954604185,고구려,55,53,1,0
1680030,9788954615525,시인,53,53,0,0
1809431,9788955471700,여우,53,53,0,0
1819284,9788955566147,작문,53,53,0,0
1856019,9788955614466,성경,56,53,0,1
1856128,9788955614473,성경,56,53,0,1
1856222,9788955614480,성경,56,53,0,1
1972089,9788956026503,유학,53,53,0,0
2021868,9788962479027,신라,53,53,0,0
2043396,9788956250960,대통령,53,53,0,0
2078822,9788956490434,샐러드,53,53,0,0
2184470,9788956744889,간략개요,53,53,0,0
2184471,9788956744889,설정,53,53,0,0
2186619,9788956745121,간략개요,53,53,0,0
2339891,9788957514856,엄마,53,53,0,0
2377352,9788957821220,비트코인,53,53,0,0
2427559,9791188230273,투자,53,53,0,0
2449823,9788957973349,호흡,53,53,0,0
2575766,9788958281412,일기,53,53,0,0
2609334,9788958284536,공룡,55,53,1,0
2701158,9788958622673,청조,53,53,0,0
2717276,9788958624882,미래,53,53,0,0
2791367,9788958851059,식물,55,53,1,0
2792370,9788958851196,광물,53,53,0,0
2879208,9788959134007,공부,53,53,0,0
2886300,9788959134502,여행,53,53,0,0

In [25]:
df[df['THREE_WGHTVAL_VALUE'] == 1].sample(5)

,ISBN_NO,WRD_NM,FQ_CO,ONE_WGHTVAL_VALUE,TWO_WGHTVAL_VALUE,THREE_WGHTVAL_VALUE
1461645,9788954408042,지성개선론,3,0,0,1
579144,9788915016521,끊어진지푸라기,3,0,0,1
1756151,9788954625241,말과활,3,0,0,1
104509,9781844285457,내토끼어딨어,3,0,0,1
1874494,9788971998441,양심경제,3,0,0,1

In [26]:
df[df['TWO_WGHTVAL_VALUE'] == 1].sample(5)

,ISBN_NO,WRD_NM,FQ_CO,ONE_WGHTVAL_VALUE,TWO_WGHTVAL_VALUE,THREE_WGHTVAL_VALUE
733738,9788925514246,신서희,2,0,1,0
1503039,9788954419581,자음과모음,2,0,1,0
2003359,9788956054490,그림책,4,2,1,0
2797612,9788958913184,오정수,2,0,1,0
1779272,9788955171570,마에다타츠히코,2,0,1,0