In [1]:
import pandas as pd

In [13]:
df1 = pd.read_csv('data/NL_LON_HALFLIFE_202008.csv')
df2 = pd.read_csv('data/NL_ON_SPECIES_ANALYSIS_MASTER_202112.csv')

c:\Users\mkh08\miniconda3\envs\py3.10\lib\site-packages\IPython\core\interactiveshell.py:3505: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\mkh08\miniconda3\envs\py3.10\lib\site-packages\IPython\core\interactiveshell.py:3505: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [31]:
df1.tail()

,SPECIES_MASTER_SEQ_NO,ISBN_NO,MUMM_LON_HALFLIFE_NO,MXM_LON_HALFLIFE_NO,AVRG_LON_HALFLIFE_NO,BOOK_CO
1050105,5687529,9788983673107,34,34,34,1
1050106,5688417,9788954672771,12,12,12,2
1050107,5690737,9788969150783,12,12,12,1
1050108,5691402,9788974461358,4183,4183,4183,1
1050109,5691407,9788970902244,4565,4565,4565,1

In [32]:
df2.tail()

,BOOK_MASTR_SEQ_NO,CTRL_NO,ISBN_THIRTEEN_NO,TITLE_NM,AUTHR_NM,PUBLISHER_NM,VLM_NM,PBLCATE_DE,IMAGE_URL,LON_CO,ISBN_ORGT_NO
1090750,2478920,KJU201012858,9788958124917,이상한 사과나무,글: 홍건국 ;그림: 손혜란,한국헤밍웨이,17,2005,NaN,1450,8958124911(v.17):
1090751,2478721,KJU201012808,9788958125181,혼자는 너무 심심해,글: 홍건국 ;그림: 김세온,한국헤밍웨이,44,2005,NaN,1050,8958125187(v.44):
1090752,2478736,KJU201012828,9788958125310,장난감 나라 대포 전쟁,글: 홍건국 ;그림: 김선민,한국헤밍웨이,57,2005,NaN,1532,8958125314(v.57):
1090753,2446221,KJU200702045,9788971962305,산수보다 쉬운 수학,"지은이: 강성오,그린이: 박향미",사계절출판사,1,1994,http://image.aladin.co.kr/product/7/9/cover/89...,944,8971962305
1090754,2556992,KJU200702045,9788971962312,산수보다 쉬운 수학,"지은이: 강성오,그린이: 박향미",사계절출판사,2,1994,https://bookthumb-phinf.pstatic.net/cover/000/...,855,8971962313:

In [45]:
# 두 데이터프레임을 머지
merged_df = pd.merge(df1, df2, left_on='SPECIES_MASTER_SEQ_NO', right_on='BOOK_MASTR_SEQ_NO', how='inner')
# merged_df = pd.merge(df1, df2, left_on='ISBN_NO', right_on='ISBN_THIRTEEN_NO', how='inner')

In [46]:
merged_df # 709475 row 살아남음  (df1 1050109, df2 1090754)

,SPECIES_MASTER_SEQ_NO,ISBN_NO,MUMM_LON_HALFLIFE_NO,MXM_LON_HALFLIFE_NO,AVRG_LON_HALFLIFE_NO,BOOK_CO,BOOK_MASTR_SEQ_NO,CTRL_NO,ISBN_THIRTEEN_NO,TITLE_NM,AUTHR_NM,PUBLISHER_NM,VLM_NM,PBLCATE_DE,IMAGE_URL,LON_CO,ISBN_ORGT_NO
0,116165,9788975486456,2492,5008,4183,9,116165,KMO200135104,9788975486456,(L=MS²학문의 기원)學習學,韓駿相 著,학지사,NaN,2001,http://image.aladin.co.kr/product/30/12/cover/...,369,8975486451
1,136707,9788952720016,3840,5631,4736,3,136707,KMO200205969,9788952720016,"잘가라, 종이만화",박석환,시공사,NaN,2001,http://image.aladin.co.kr/product/30/7/cover/8...,103,8952720016
2,116168,9788976820624,534,6098,4553,37,116168,KMO200135105,9788976820624,골콘다,존 브룩스 지음;이동진 옮김,그린비,NaN,2001,http://image.aladin.co.kr/product/30/4/cover/8...,837,8976820622
3,116171,9788977990401,562,6483,4212,52,116171,KMO200135087,9788977990401,건축기술 실무이야기:건축구조·시공/신기술·신공법,삼성물산 건설부문 저,공간예술사,NaN,2001,http://image.aladin.co.kr/product/28/98/cover/...,1234,8977990408
4,116175,9788972783497,2293,3175,2715,5,116175,KMO200135089,9788972783497,(일상으로 본)조선시대 이야기,정연식 지음,청년사,NaN,2001,NaN,152,8972783498(세트)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709471,5683211,9791196861162,12,12,12,1,5683211,KMO202038738,9791196861162,트렌드 읽는 습관,"김선주,안현정 지음",좋은습관연구소,NaN,2020,https://image.aladin.co.kr/product/24211/79/co...,702,NaN
709472,5683275,9791158681753,32,32,32,3,5683275,KJU202007427,9791158681753,빙하섬을 지켜 주세요,글·그림: 이새미,책먹는아이,NaN,2020,https://image.aladin.co.kr/product/24217/12/co...,3055,NaN
709473,5686627,9791164135592,30,30,30,3,5686627,KJU201910254,9791164135592,흔한남매,원작: 흔한남매 ;그림: 유난희,미래엔,5,2019,https://image.aladin.co.kr/product/24307/73/co...,28685,NaN
709474,5688417,9788954672771,12,12,12,2,5688417,KMO202036801,9788954672771,일곱 해의 마지막 :김연수 장편소설,지은이: 김연수,문학동네,NaN,2020,https://image.aladin.co.kr/product/24292/56/co...,7969,NaN
709475,5690737,9788969150783,12,12,12,1,5690737,KMO202055328,9788969150783,(이야기가 있는) 방언사전,"박미연,금성원 지음",학교도서관저널,NaN,2020,https://image.aladin.co.kr/product/24297/55/co...,110,NaN